// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqiyhhongzkplaxndvgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxaXloaG9uZ3prcGxheG5kdmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTk1NDAsImV4cCI6MjA2NjA5NTU0MH0.Y7snv1KK4X9DZdxge-UfLbWmgWkREML-a4_N6fSluQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);